### ISSUE TITLE
In branch rc_v0.0.3 add semantic-ui remove w2ui

### ISSUE THREAD

**Issue by NorthDecoder** [Tacoma-JS/Tacoma-JS.github.io#14]
@topcheese requests much prettier interface [semantic-ui](http://semantic-ui.com/) instead of [w2ui](http://w2ui.com/web/)

**Comment by charliewilco** [comment]
@topcheese @NorthDecoder let me worry about this.

**Comment by charliewilco** [comment]
the final UI will look more like this...

http://codepen.io/charlespeters/pen/vgqGyP

**Comment by topcheese** [comment]
@charlespeters, is this for the main branch, or for the alternative SUI + GunJS site?
http://codepen.io/charlespeters/pen/vgqGyP

**Comment by charliewilco** [comment]
@topcheese this is for the main site we're building. i'm taking care of the design & content, we'll go through this at our next meeting. don't worry about a thing 😀

**Comment by NorthDecoder** [comment]
We have several branches going just for educational purposes.  Each branch can run separately from the others so we can test and critique the different versions without affecting the good work @charlespeters is doing on branch rc_v0.1.0.  So when there is a requested change in a branch that is not affecting ones work specifically then there is no need to worry about the other branches for example @topcheese .  This I hope is in the spirit of open source collaboration.

The added collaborators also allow us to exercise the project management tools on github and demonstrate git function.

**Comment by charliewilco** [comment]
we never talked about that at all

**Comment by topcheese** [comment]
Joe and I met,  and the notes are listed with the new branches.  It didn't
seem that Charles was aware, so I mentioned it.  I'm open to help out on
the main branch,  but since I'm new it's best to work on a branch. I'm also
open to any other suggestions?

**Comment by charliewilco** [comment]
@NorthDecoder @topcheese what you're describing isn't the purpose of branches, branches are quick and disposable by nature. a better idea is if you forked the project.

the conversation i had with @NorthDecoder last saturday was to build a site with a core focus on content to promote tacoma.js and consolidate all the information between meetup.com, github and the other silos of information. the other thing he and i discussed was that everything that exists is placeholder until a site is built. the site we're building will be a statically generated site via [metalsmith](http://www.metalsmith.io/), hosted on github pages and compiled with modern build tools. the other extraneous purpose was an artifact that exemplifies best practices.

if you want to contribute, let's sit and talk at the meetup on saturday afternoon.

**Comment by topcheese** [comment]
Sounds good!
