### ISSUE TITLE
In branch rc_v0.0.2 add a script loader

### ISSUE THREAD

**Issue by NorthDecoder** [Tacoma-JS/Tacoma-JS.github.io#7]
Thanks to @charlespeters for the gentle comment that scripts added in the index file without a loader will lead to unorganized script dependencies which will then lead to failures due to the asynchronous nature of script loading.  Try something like [requirejs](http://requirejs.org/) .

**Comment by charliewilco** [comment]
@NorthDecoder use [webpack](https://webpack.js.org/), [require.js](http://jrburke.com/2016/03/17/requirejs-2.2-alameda-1.0-released/) has largely been abandoned

**Comment by NorthDecoder** [comment]
Thanks, I will take a look at webpack :smile: This still needs to be addressed by moving requirejs out of the code base.
